# Generated by Django 5.1.4 on 2024-12-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='image',
            field=models.ImageField(default='', upload_to='backgrounds/'),
            preserve_default=False,
        ),
    ]
