# Generated by Django 5.1.4 on 2024-12-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_activities_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='image',
            field=models.ImageField(null=True, upload_to='backgrounds/'),
        ),
    ]
