# Generated by Django 5.1.4 on 2024-12-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_activities_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='Where',
            field=models.CharField(default='', help_text='Eter the Activity Place', max_length=225),
            preserve_default=False,
        ),
    ]
