# Generated by Django 5.1.4 on 2024-12-27 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_activities_where'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='places',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
