# Generated by Django 5.1.4 on 2024-12-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_activities_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='highlights',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
