# Generated by Django 5.1.4 on 2024-12-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_activities_highlights'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='activities',
            name='highlights',
        ),
        migrations.AddField(
            model_name='activities',
            name='highlights',
            field=models.ManyToManyField(blank=True, to='main.highlight'),
        ),
    ]
